" -------------------------------
" NeoBundle
" -------------------------------
if has('vim_starting')
  if &compatible
    set nocompatible
  endif

  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle'))

NeoBundleFetch 'Shougo/neobundle.vim'

" ディレクトリをツリー表示
NeoBundle 'scrooloose/nerdtree'
" Vimの画面の一番下にあるステータスラインの表示内容が強化される
NeoBundle 'itchyny/lightline.vim'
" インデントに色をつけてくれる
NeoBundle 'Yggdroot/indentLine'
" 各行の行末に不要に入ってしまったスペースを色つけて表示する
NeoBundle 'bronson/vim-trailing-whitespace'
" 入力途中のコードを自動で補完する
NeoBundle 'Shougo/neosnippet.vim'
NeoBundle 'Shougo/neosnippet-snippets'
" ファイルオープンを便利に
NeoBundle 'Shougo/unite.vim'
" Unite.vimで最近使ったファイルを表示できるようにする
NeoBundle 'Shougo/neomru.vim'
" 自動で閉じる
NeoBundle 'tpope/vim-endwise'
" Vimの中でGitのコマンドを実行
NeoBundle 'tpope/vim-fugitive'


"" front
" コード補完の機能
NeoBundle 'Shougo/neocomplete.vim'
" HTMLやCSSのタグや属性を色付けする
NeoBundle 'tomasr/molokai'
" HTML5のタグに色がつく
NeoBundle 'othree/html5.vim'
" CSS3の内容に色がつく
NeoBundle 'hail2u/vim-css3-syntax'
" JavaScriptのコードに色がつく
" NeoBundle 'jelera/vim-javascript-syntax'
NeoBundle 'othree/yajs.vim'
" HTML5の文法チェック
NeoBundle 'hokaccha/vim-html5validator'
" emmet
NeoBundle 'mattn/emmet-vim'
" sassやscssのファイルへの色づけ
NeoBundle 'AtsushiM/search-parent.vim'
NeoBundle 'AtsushiM/sass-compile.vim'
" coffee-script
NeoBundle 'kchmck/vim-coffee-script'
" jsx syntax
NeoBundle 'mxw/vim-jsx'


call neobundle#end()
filetype plugin indent on
NeoBundleCheck

""""""""""""""""""""""""""""""
" mxw/vim-jsx
""""""""""""""""""""""""""""""
let g:jsx_ext_required = 0

""""""""""""""""""""""""""""""
" sass-compile
""""""""""""""""""""""""""""""
" 編集したファイルから遡るフォルダの最大数
let g:sass_compile_cdloop = 5
" ファイル保存時に自動コンパイル（1で自動実行）
let g:sass_compile_auto = 0
" 自動コンパイルを実行する拡張子
let g:sass_compile_file = ['scss', 'sass']
" cssファイルが入っているディレクトリ名（前のディレクトリほど優先）
let g:sass_compile_cssdir = ['css', 'stylesheet']
" コンパイル実行前に実行したいコマンドを設定
" 例：growlnotifyによる通知
" let g:sass_compile_beforecmd = "growlnotify -t 'sass-compile.vim' -m 'start sass compile.'"
" コンパイル実行後に実行したいコマンドを設定
" 例：growlnotifyによる通知(${sasscompileresult}は実行結果)
" let g:sass_compile_aftercmd = "growlnotify -t 'sass-compile.vim' -m ${sasscompileresult}"


""""""""""""""""""""""""""""""
" NERDTree
""""""""""""""""""""""""""""""
let g:NERDTreeShowBookmarks=1
autocmd VimEnter * NERDTree
" autocmd StdinReadPre * let s:std_in=1
" autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" --------------------------------
" unite.vim
" neomru.vim
" --------------------------------
" バッファ一覧
" noremap <C-P> :Unite buffer<CR>
" 最近使ったファイルの一覧
noremap <C-Z> :Unite file_mru<CR>
" ESCキーを2回押すと終了する
au FileType unite nnoremap <silent> <buffer> <ESC><ESC> :q<CR>
au FileType unite inoremap <silent> <buffer> <ESC><ESC> <ESC>:q<CR>
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"


" --------------------------------
" neocomplete.vim
" --------------------------------
let g:acp_enableAtStartup = 0
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
if !exists('g:neocomplete#force_omni_input_patterns')
  let g:neocomplete#force_omni_input_patterns = {}
endif


" --------------------------------
" 基本設定
" --------------------------------
" vim内部で使われる文字エンコーディングをutf-8に設定する
set encoding=utf-8

" 想定される改行コードの指定する
set fileformats=unix,dos,mac

" ハイライトを有効化する
syntax enable

" 挿入モードでTABを挿入するとき、代わりに適切な数の空白を使う
set expandtab

" 新しい行を開始したとき、新しい行のインデントを現在行と同じにする
set autoindent


" スワップファイルは使わない(ときどき面倒な警告が出るだけで役に立ったことがない)
set noswapfile
" カーソルが何行目の何列目に置かれているかを表示する
set ruler
" コマンドラインに使われる画面上の行数
set cmdheight=2
" エディタウィンドウの末尾から2行目にステータスラインを常時表示させる
set laststatus=2
" ステータス行に表示させる情報の指定(どこからかコピペしたので細かい意味はわかっていない)
set statusline=%<%f\ %m%r%h%w%{'['.(&fenc!=''?&fenc:&enc).']['.&ff.']'}%=%l,%c%V%8P
" ウインドウのタイトルバーにファイルのパス情報等を表示する
set title
" コマンドラインモードで<Tab>キーによるファイル名補完を有効にする
set wildmenu
" 入力中のコマンドを表示する
set showcmd
" バックアップディレクトリの指定(でもバックアップは使ってない)
"set backupdir=$HOME/.vimbackup
" バッファで開いているファイルのディレクトリでエクスクローラを開始する(でもエクスプローラって使ってない)
set browsedir=buffer
" 小文字のみで検索したときに大文字小文字を無視する
set smartcase
" 検索結果をハイライト表示する
set hlsearch
" 暗い背景色に合わせた配色にする
set background=dark
" タブ入力を複数の空白入力に置き換える
set expandtab
" 検索ワードの最初の文字を入力した時点で検索を開始する
set incsearch
" 保存されていないファイルがあるときでも別のファイルを開けるようにする
set hidden
" 不可視文字を表示する
set list
" タブと行の続きを可視化する
set listchars=tab:>\ ,extends:<
" 行番号を表示する
set number
" 対応する括弧やブレースを表示する
set showmatch
" 改行時に入力された行の末尾に合わせて次の行のインデントを増減する
set smartindent
" タブ文字の表示幅
set tabstop=2
" Vimが挿入するインデントの幅
set shiftwidth=2
" 行頭の余白内で Tab を打ち込むと、'shiftwidth' の数だけインデントする
set smarttab
" カーソルを行頭、行末で止まらないようにする
set whichwrap=b,s,h,l,<,>,[,]
" カラースキーマの指定
colorscheme desert
" 行番号の色
highlight LineNr ctermfg=darkyellow
set backspace=indent,eol,start
" インデント幅をスペース2つ分にする
set shiftwidth=2
" インデントによって自動で折りたたみ
" set foldmethod=indent

