" -------------------------------
" NeoBundle
" -------------------------------
if has('vim_starting')
  if &compatible
    set nocompatible
  endif

  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle'))

NeoBundleFetch 'Shougo/neobundle.vim'



" Vimの画面の一番下にあるステータスラインの表示内容が強化される
NeoBundle 'itchyny/lightline.vim'

" HTMLやCSSのタグや属性を色付けする
NeoBundle 'tomasr/molokai'

" インデントに色をつけてくれる
NeoBundle 'nathanaelkane/vim-indent-guides'

" 各行の行末に不要に入ってしまったスペースを色つけて表示する
NeoBundle 'bronson/vim-trailing-whitespace'

" 入力途中のコードを自動で補完する
NeoBundle 'Shougo/neosnippet.vim'
NeoBundle 'Shougo/neosnippet-snippets'

" コード補完の機能
NeoBundle 'Shougo/neocomplete.vim'

" HTML5のタグに色がつく
NeoBundle 'othree/html5.vim'

" CSS3の内容に色がつく
NeoBundle 'hail2u/vim-css3-syntax'

" JavaScriptのコードに色がつく
NeoBundle 'jelera/vim-javascript-syntax'

" HTML5の文法チェック
NeoBundle 'hokaccha/vim-html5validator'

" emmet
NeoBundle 'mattn/emmet-vim'

" sassやscssのファイルへの色づけ
NeoBundle 'AtsushiM/sass-compile.vim'

" Vimの中でGitのコマンドを実行
NeoBundle 'tpope/vim-fugitive'

" coffee-script
NeoBundle 'kchmck/vim-coffee-script'


call neobundle#end()
filetype plugin indent on
NeoBundleCheck


